project:
  type: website
  output-dir: docs

website:
  title: "Welcome to my webpage"
  navbar: 
    left:
      - text: "Menu"
        menu:
          - href: index.qmd
            text: Data Story
          - href: about.qmd
            text: About
      - href: index.qmd
        text: Data Story
      - href: about.qmd
        text: About
      - href: Shiny.qmd
        text: Draft
        
    
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    grid:
        sidebar-width: 350px

editor: visual

