---
title: "Week-6: Code-along"
author: "NM2207: Computational Media Literacy"
date: "`r Sys.Date()`"
output:
  html_document:
  df_print: paged
pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# II. Code to edit and execute using the Code-along-6.Rmd file 
<br>

## A. `for` loop
<br>

### 1. Simple `for` loop (Slide #6)

```{r, eval=TRUE,echo=TRUE}
# Enter code here
for (x in c(3, 6, 9)) {
  print(x)
}
```
<br>

### 2. `for` loops structure (Slide #7)

```{r, eval=TRUE,echo=TRUE}
# Left-hand side code: for loop for passing values
for (x in 1:8) {print(x)}
```
<br>
```{r, eval=TRUE,echo=TRUE}
# Right-hand side code: for loop for passing indices
for (x in 1:8)
{y<- seq(from=100, to=200, by=5)
print(y[x])}
```
<br>

### 3. Example: find sample means (Slide #9)

```{r, eval=TRUE,echo=TRUE}
# Enter code here
# Create a vector of the sample_size we want to use
sample_sizes <- c(5, 10, 15, 20, 25000)

# Initialise output vector with zero, replacing each zero with the mean that we are calculating
sample_means <-double(length(sample_sizes))

# Generate indices as many as the length of the vector (similar to 1:5)
for (i in seq_along(sample_sizes)) {
  sample_means[[i]] <-mean(rnorm(sample_sizes[[i]]))
}
sample_means
```
<br>

### 4. Alternate ways to pre-allocate space (Slide #12) To hold different data types

```{r, eval=TRUE,echo=TRUE}
# Example 3 for data_type=double
sample_means <- rep(0, length(sample_sizes))
```
<br>

```{r, eval=TRUE,echo=TRUE}
# Initialisation of data_list
data_list <- vector("list", length=5)
```
<br>

### 5. Review: Vectorized operations (Slide #18)

```{r, eval=TRUE,echo=TRUE}
# Example: bad idea!
a <- 7:11
b <- 8:12
out<-rep(0L,5)
for (i in seq_along(a)) {
  out[i] <-a[i] + b[i]
}
out
```
<br>

```{r, eval=TRUE,echo=TRUE}
# Taking advantage of vectorization
a <- 7:11
b <- 8:12
out <- a+b
out
```
<br>

## B. Functionals

### 6. `for` loops vs Functionals (Slides #23 and #24)

```{r, eval=TRUE,echo=TRUE}
# Slide 23
sample_sizes <- c(5, 10, 15, 20, 25000)
fsd <-function(sample_sizes) {
  sample_sds <-rep(0, length(sample_sizes))
  for(i in seq_along(sample_sizes)) {
    sample_sds[i] <-sd(rnorm(sample_sizes[1]))
  }
  return(sample_sds)
}
fsd(sample_sizes)

```
<br>

```{r, eval=TRUE,echo=TRUE}
# Slide 24
#Compute mean
sample_sizes <- c(5, 10, 15, 20, 25000)
sample_summary <-function(sample_sizes, fun) {
  out<-vector("double", length(sample_sizes))
  for (i in seq_along(sample_sizes)) {
    out[i]<-fun(rnorm(sample_sizes[i]))
  }
return(out)
}
sample_summary(sample_sizes, mean)
# Compute median
sample_summary(sample_sizes, median)
# Compute sd
sample_summary(sample_sizes, sd)
```
<br>

## C. `while` loop

### 7. `while` loop (Slides #27)

```{r, eval=TRUE,echo=TRUE}
# Left-hand side code: for loop
for(i in 1:5){
  print(i)
}
```
<br>

```{r, eval=TRUE,echo=TRUE}
# Right-hand side code: while loop
i<-1
while(i <=5){
  print(i)
  i<- i +1
}
```
<br>

```{r, eval=TRUE,echo=TRUE}
library(tidyverse)
read_csv("titanic.csv")

titanic<-read_csv("titanic.csv")
```

```{r, eval=TRUE,echo=TRUE}

filtered_titanic<- (titanic %>%
filter(Pclass==3,
Survived>=1))



ggplot(filtered_titanic) +
aes(x=Age,y=PassengerId) +
geom_point() +
labs(x="Age of the survivor in Class 3",
y="PassengerID",
title="Age of the survivors in class 3 versus their passenger id")




```
```{r, eval=TRUE,echo=TRUE}
carName <- 3

print_car_name <- function(){

names<-c("Volvo", "Mercedes", "Audi", "BMW")

carName<-names[carName]

return(carName)

}

cat("the name of the car you chose is", print_car_name(),", but the value of the variable carName is", carName)






```

```{r, eval=TRUE,echo=TRUE}

guess<-16
guessNum<-function(guess){
  answer<-15
  print(guess)
  print(answer)
  number<-guess
 Message<- ifelse(number==15, "Right Answer",
 ifelse(number<15, "Below Answer", "Above Answer"))
cat("Your answer is:", Message)
 }
guessNum(30)




  





```
